version: '3.4'

services:
  web:
    build: .
    hostname: dev-businesscard
    ports:
      - "8080:8080"
    links:
      - mysql_businesscard
    environment:
      - TEQUILA_HOST=test-tequila.epfl.ch
      - MOCK_ORACLE=1
      - SITE_URL=localhost:8080
    volumes:
      - ./dbs-dev.conf:/opt/dinfo/etc/dbs.conf

  mysql_businesscard:
    image: mysql:5.5
    hostname: mysql-businesscard
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=businesscard
      - MYSQL_USER=businesscard
      - MYSQL_PASSWORD=businesscard
    volumes:
      - ./conf/docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - "23306:3306"