version: '3.4'

services:
  web:
    build: .
    hostname: dev-businesscard
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql_businesscard
    environment:
      - TERM=xterm
      - TZ=Europe/Zurich
      - PERL5LIB=/opt/dinfo/lib/perl
      - DATABASE_ACCRED_NAME=accred
      - DATABASE_ACCRED_HOST=mysql_businesscard
      - DATABASE_ACCRED_USER=businesscard
      - DATABASE_ACCRED_PWD=businesscard
      - DATABASE_BUSINESSCARD_NAME=businesscard
      - DATABASE_BUSINESSCARD_HOST=mysql_businesscard
      - DATABASE_BUSINESSCARD_USER=businesscard
      - DATABASE_BUSINESSCARD_PWD=businesscard
      - DATABASE_DINFO_NAME=dinfo
      - DATABASE_DINFO_HOST=mysql_businesscard
      - DATABASE_DINFO_USER=businesscard
      - DATABASE_DINFO_PWD=businesscard
      - TEQUILA_HOST=test-tequila.epfl.ch
      - MOCK_ORACLE=1

  mysql_businesscard:
    image: mysql:5.5
    hostname: mysql-businesscard
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=businesscard
      - MYSQL_USER=businesscard
      - MYSQL_PASSWORD=businesscard
    volumes:
      - ./conf/docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - "23306:3306"