version: '3.4'

services:
  businesscard_web:
    build: .
    hostname: businesscard_web
    container_name: businesscard_web
    ports:
      - "8080:8080"
    links:
      - businesscard_mysql
    environment:
      - TEQUILA_HOST=test-tequila.epfl.ch
      - MOCK_ORACLE=1
      - SITE_URL=localhost:8080
      # Override default value from docker-compose
      - TEQUILA_REDIRECT_PORT=8080
    volumes:
      - ./dbs-dev.conf:/opt/dinfo/etc/dbs.conf
      - ./cgi-bin/businesscard:/var/www/cgi-bin/businesscard

  businesscard_mysql:
    image: mysql:5.5
    hostname: businesscard_mysql
    container_name: businesscard_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=businesscard
      - MYSQL_USER=businesscard
      - MYSQL_PASSWORD=businesscard
    volumes:
      # See `make initdb` in Makefile:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "23306:3306"
