$tmpl_labels = {
	wrong_params => {
		fr	=> qq{Paramètres non conformes},
		en	=> qq{Illegal parameters},
	},
	no_access => {
		fr	=> qq{Pas de droits d'accès},
		en	=> qq{No access rights},
	},
	no_funds => {
		fr	=> qq{Aucun fonds disponible},
		en	=> qq{No funds available},
	},
	no_users => {
		fr	=> qq{Aucune personne sous votre contrôle},
		en	=> qq{No person under your management},
	},
	no_rights => {
		fr	=> qq{Pas de droits de gestion},
		en	=> qq{No management rights},
	},
	init_templ => {
		fr	=> qq{Erreur affichage page},
		en	=> qq{Page display error},
	},

	orders_label => {
		fr	=> qq{Commandes de cartes de visite},
		en	=> qq{Businesscard orders},
	},
	prix => {
		fr	=> qq{Prix},
		en	=> qq{Price},
	},
	responsable => {
		fr	=> qq{Responsable repro},
		en	=> qq{Reprography contact},
	},	
	cards => {
		fr	=> qq{Cartes de visite},
		en	=> qq{Business cards},
	},
	card_lang_note1 => {
		fr	=> qq{Langue du contenu de la carte de visite},
		en	=> qq{Businesscard Content language},
	},	
	card_lang_note2 => {
		fr	=> qq{Choisir la langue du contenu, puis, cliquer sur l'accréditation choisie, si plusieurs},
		en	=> qq{Select Businesscard Content language, then, choose an accreditaion, if more available},
	},	
	accreds_txt => {
		fr	=> qq{Accréditations},
		en	=> qq{Accreditations},
	},	

	title1 => {
		fr	=> qq{Commande de cartes de visite},
		en	=> qq{Business cards order},
	},
	neworder => {
		fr	=> qq{Nouvelle commande},
		en	=> qq{New command},
	},
	delete_label => {
		fr	=> qq{Annuler},
		en	=> qq{Delete},
	},
	delete_confirm => {
		fr	=> qq{Annuler cette commande},
		en	=> qq{Delete this order},
	},
	dem_valid => {
		fr	=> qq{Demande de validation},
		en	=> qq{Validation request},
	},
	commander => {
		fr	=> qq{Valider et Commander},
		en	=> qq{Validate and Submit},
	},
	show => {
		fr	=> qq{Visualiser},
		en	=> qq{Preview},
	},
	del_note => {
		fr	=> qq{Commande effacée :},
		en	=> qq{Order deleted},
	},
	repro_en_cours => {
		fr	=> qq{En cours},
		en	=> qq{Start Processing},
	},
	repro_done => {
		fr	=> qq{Commande terminée},
		en	=> qq{Processed},
	},
	db_error => {
		fr	=> qq{Erreur base de données},
		en	=> qq{Database error},
	},
	quantite_label => {
		fr	=> qq{Quantité},
		en	=> qq{Quantity},
	},
	person_not_found => {
		fr	=> qq{Personne pas trouvée ou sans droit pour commander des cartes de visite},
		en	=> qq{Person not found or no rights to order EPFL businesscards},
	},
	cmd_not_found => {
		fr	=> qq{Commande inconnue},
		en	=> qq{Order not found},
	},
	no_fund => {
		fr => qq{Numéro de fonds absent},
		en => qq{Fund numer missing},
	},
	fix	=> {
		fr	=> qq{Corriger},
		en	=> qq{Modify},
	},
	done_send_note	=> {
		fr	=> qq{Commander la carte de visites ci-dessus. A partir de ce stade, plus aucune correction possible! },
		en	=> qq{
		},
	},
	label_status	=> {
		fr	=> qq{Etat},
		en	=> qq{Status},
	},
	label_by_status	=> {
		fr	=> qq{Par état},
		en	=> qq{By status},
	},
	label_search_people	=> {
		fr	=> qq{Chercher une personne},
		en	=> qq{Search people},
	},
	label_search_cmd=> {
		fr	=> qq{Chercher une commande},
		en	=> qq{Search order},
	},
	label_order=> {
		fr	=> qq{Passer une commande},
		en	=> qq{Order businesscards},
	},
	label_description=> {
		fr	=> qq{Description du contenu du verso de la carte de visite},
		en	=> qq{Businesscard content description, verso side},
	},
	label_commande	=> {
		fr	=> qq{Commande},
		en	=> qq{Order},
	},

	label_fond	=> {
		fr	=> qq{Fonds},
		en	=> qq{Fund},
	},
	label_path1	=> {
		fr	=> qq{<b>Niveau 2 (2 lignes)</b>},
		en	=> qq{<b>Level 2 (2 lines)</b>},
	},
	label_path2	=> {
		fr	=> qq{Institut, Labo ou Service},
		en	=> qq{Institute, Lab or Service},
	},
	label_title	=> {
		fr	=> qq{Titre universitaire},
		en	=> qq{Title},
	},
	label_firstname=> {
		fr	=> qq{Prénom},
		en	=> qq{Firstname},
	},
	label_name	=> {
		fr	=> qq{Nom},
		en	=> qq{Name},
	},
	label_function	=> {
		fr	=> qq{Fonction},
		en	=> qq{Position},
	},
	label_phone	=> {
		fr	=> qq{Tél.},
		en	=> qq{Phone},
	},
	label_mail	=> {
		fr	=> qq{Mail},
		en	=> qq{Mail},
	},
	label_type	=> {
		fr	=> qq{Type cartes de visite},
		en	=> qq{Businesscard type},
	},
	label_select	=> {
		fr	=> qq{choisir une personne},
		en	=> qq{select a person},
	},
	main_note => {
		fr	=> qq{<b>Attention :</b>
		<ul>
		<li>Le délai de production est de maximum cinq jours ouvrés.<br>
		<li>Veuillez consulter <a href="http://www.epfl.ch/repro/"><b>les horaires d'ouverture</b></a> du Centre d'impression
		</ul>},
		en	=> qq{<b>Note :</b>
		<ul>
		<li>Processing time is max 5 working days.<br>
		<li>Please check the <a href="http://www.epfl.ch/repro/"><b>open hours</b></a> of the Print Center
		</ul>},
	},	
	repro_en_cours_note => {
		fr	=> qq{Traiter la commande},
		en	=> qq{Start command processing},
	},
	dem_valid_note => {
		fr => qq{Cette demande de carte de visite selon la présentation ci-dessus sera soumise pour approbation à		},
		en => qq{This request for businesscards order will be submitted for validation to},
	},
	dem_valid_done_note => {
		fr => qq{Cette demande de carte de visite selon la présentation ci-dessus a été soumise pour approbation à },
		en => qq{This request for businesscards order has been submitted for validation to },
	},
	mod_note => {
		fr => qq{Vous pouvez modifier le contenu et/ou la présentation et suivre de nouveau le processus de validation et soumission tant que la commande n'ait pas été mise en traitement par la Repro},
		en => qq{You can modify this businesscard and re-activate the validation process as long as the order has not been processed},
	},
	validate_note => {
		fr => qq{Sélectionner un fonds pour Valider et soumettre la commande de cartes de visite},
		en => qq{Select a fund to Validate and Submit businesscards order},
	},
	fund_select => {
		fr => qq{Sélectionner un fonds },
		en => qq{Select a fund },
	},
	queue_note => {
		fr => qq{La commande ci-dessus a été transmise à la Reprographie pour impression.<br>},
		en => qq{This Businesscards order has been submitted for processing to the Printing Service},
	},
	done_note => {
		fr => qq{Cette commande est terminée },
		en => qq{This order has been processed },
	},
	list_empty_note => {
		fr => qq{Aucune commande dans cet état},
		en => qq{No order for this status},
	},
	corp_ident => {
		fr => qq{Identité Visuelle},
		en => qq{Corporate Identity},
	},
	corp_ident_quest => {
		fr => qq{Questions sur le visuel},
		en => qq{Questions about Corporate Identity},
	},
	repro_quest => {
		fr => qq{Questions sur les délais/quantités},
		en => qq{Questions about duration/quantities},
	},
	repro_prix => {
		fr => qq{Prix: 50 ex. CHF 15.-, 100 ex. CHF 25.-, 200 ex. CHF 30.-, 300 ex. CHF 35.-},
		en => qq{Price: 50 pcs. CHF 15.-, 100 pcs. CHF 25.-, 200 pcs. CHF 30.-, 300 pcs. CHF 35.-},
	},	
};
